export DATABASE_URL='postgresql://postgres_deployment_capstone_ankita_user:u68XDYDJhI3FxlCGiWz2MMhFR9YEU1dO@dpg-che17abhp8ubgo1m13jg-a.oregon-postgres.render.com/postgres_deployment_capstone_ankita'
export token='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZxUjQtclBmdEEwUkhFNEpyLWNKeCJ9.eyJpc3MiOiJodHRwczovL2F2LWZzbmQudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY0MTBjYTM3YTQ3MmZlNjI2NWU1NWNjNyIsImF1ZCI6ImNhcHN0b25lIiwiaWF0IjoxNjgzODM1NDY4LCJleHAiOjE2ODM4OTE0NjgsImF6cCI6Im1GeDNoZjltalRkZnhuNmZhVTBCSk9rTWJxUkdqdUdhIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJkZWxldGU6YWN0b3JzIiwiZGVsZXRlOm1vdmllcyIsImdldDphY3RvcnMiLCJnZXQ6bW92aWVzIiwicGF0Y2g6YWN0b3JzIiwicGF0Y2g6bW92aWVzIiwicG9zdDphZGQtYWN0b3IiLCJwb3N0OmFkZC1tb3ZpZSJdfQ.Ith6bB9pqzCepf8DOhscYTtluUpMbYBu6cg2Ey3-N_MPxjU_umxnQODVDYmZeneQeFd3-vpGSpJQdLjsPIAZ1VrCwKbH7_uWzncgpG0s_VQMAb-g4ETQTzAtoHMWbCcmaLUr2iShH4Ari0rKVSF4u1jXcW6SGJOz2qbIxlEsPXB_ToJI3i5_IcB4oYE_vY1Rakn6r30airNbOCuRRe-Mz2-tveQroxjSmqN4M8udhHS7HTEWV6RKjPMLfYcsOsYb-HN3jloOhY3UVtfotszEWjlhwhrxJDQQTNKli0xdRPYgcvh8fz01iX2rUpM3uuKIfIKZYvt_VFV9LmCRsyVDoQ'
export AUTH0_DOMAIN='av-fsnd.us.auth0.com'
export ALGORITHMS=['RS256']
export API_AUDIENCE='capstone'
export CLIENT_ID='mFx3hf9mjTdfxn6faU0BJOkMbqRGjuGa'
export callbackURL='http://localhost:8080/login-results'
